{"created": 1582887901.9824262, "duration": 0.7450838088989258, "exitcode": 1, "root": "/Users/patelk2/python/projects/job-board", "environment": {"Python": "3.7.6", "Platform": "Darwin-19.3.0-x86_64-i386-64bit", "Packages": {"pytest": "3.7.1", "py": "1.8.1", "pluggy": "0.13.1"}, "Plugins": {"json-report": "0.7.0", "metadata": "1.8.0"}}, "summary": {"failed": 56, "total": 56}, "collectors": [{"nodeid": "", "outcome": "passed", "children": [{"nodeid": "jobs/__init__.py", "type": "Package"}, {"nodeid": "tests/__init__.py", "type": "Package"}]}, {"nodeid": "jobs/__init__.py", "outcome": "passed", "children": []}, {"nodeid": "tests/test_module1.py", "outcome": "passed", "children": [{"nodeid": "tests/test_module1.py::test_app_import_flask_module1", "type": "Function", "path": "tests/test_module1.py", "lineno": 6, "domain": "test_app_import_flask_module1"}, {"nodeid": "tests/test_module1.py::test_app_create_flask_app_module1", "type": "Function", "path": "tests/test_module1.py", "lineno": 13, "domain": "test_app_create_flask_app_module1"}, {"nodeid": "tests/test_module1.py::test_index_template_module1", "type": "Function", "path": "tests/test_module1.py", "lineno": 18, "domain": "test_index_template_module1"}, {"nodeid": "tests/test_module1.py::test_app_index_route_function_module1", "type": "Function", "path": "tests/test_module1.py", "lineno": 25, "domain": "test_app_index_route_function_module1"}, {"nodeid": "tests/test_module1.py::test_app_route_decoractors_module1", "type": "Function", "path": "tests/test_module1.py", "lineno": 35, "domain": "test_app_route_decoractors_module1"}]}, {"nodeid": "tests/test_module2.py", "outcome": "passed", "children": [{"nodeid": "tests/test_module2.py::test_layout_template_module2", "type": "Function", "path": "tests/test_module2.py", "lineno": 7, "domain": "test_layout_template_module2"}, {"nodeid": "tests/test_module2.py::test_add_bulma_css_framework_module2", "type": "Function", "path": "tests/test_module2.py", "lineno": 11, "domain": "test_add_bulma_css_framework_module2"}, {"nodeid": "tests/test_module2.py::test_add_custom_css_module2", "type": "Function", "path": "tests/test_module2.py", "lineno": 16, "domain": "test_add_custom_css_module2"}, {"nodeid": "tests/test_module2.py::test_add_fontawesome_module2", "type": "Function", "path": "tests/test_module2.py", "lineno": 21, "domain": "test_add_fontawesome_module2"}, {"nodeid": "tests/test_module2.py::test_extend_base_template_module2", "type": "Function", "path": "tests/test_module2.py", "lineno": 30, "domain": "test_extend_base_template_module2"}]}, {"nodeid": "tests/test_module3.py", "outcome": "passed", "children": [{"nodeid": "tests/test_module3.py::test_app_import_sqlite_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 6, "domain": "test_app_import_sqlite_module3"}, {"nodeid": "tests/test_module3.py::test_app_import_g_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 10, "domain": "test_app_import_g_module3"}, {"nodeid": "tests/test_module3.py::test_app_db_path_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 14, "domain": "test_app_db_path_module3"}, {"nodeid": "tests/test_module3.py::test_app_open_connection_get_attribute_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 19, "domain": "test_app_open_connection_get_attribute_module3"}, {"nodeid": "tests/test_module3.py::test_app_open_connection_connection_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 24, "domain": "test_app_open_connection_connection_module3"}, {"nodeid": "tests/test_module3.py::test_app_open_connection_row_factory_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 35, "domain": "test_app_open_connection_row_factory_module3"}, {"nodeid": "tests/test_module3.py::test_app_execute_sql_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 45, "domain": "test_app_execute_sql_module3"}, {"nodeid": "tests/test_module3.py::test_app_execute_sql_parameters_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 51, "domain": "test_app_execute_sql_parameters_module3"}, {"nodeid": "tests/test_module3.py::test_app_execute_sql_execute_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 59, "domain": "test_app_execute_sql_execute_module3"}, {"nodeid": "tests/test_module3.py::test_app_execute_sql_results_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 64, "domain": "test_app_execute_sql_results_module3"}, {"nodeid": "tests/test_module3.py::test_app_close_connection_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 77, "domain": "test_app_close_connection_module3"}, {"nodeid": "tests/test_module3.py::test_app_close_connection_decorator_module3", "type": "Function", "path": "tests/test_module3.py", "lineno": 83, "domain": "test_app_close_connection_decorator_module3"}]}, {"nodeid": "tests/test_module4.py", "outcome": "passed", "children": [{"nodeid": "tests/test_module4.py::test_template_macros_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 6, "domain": "test_template_macros_module4"}, {"nodeid": "tests/test_module4.py::test_show_job_macro_definition_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 10, "domain": "test_show_job_macro_definition_module4"}, {"nodeid": "tests/test_module4.py::test_show_job_macro_html_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 15, "domain": "test_show_job_macro_html_module4"}, {"nodeid": "tests/test_module4.py::test_show_job_macro_header_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 23, "domain": "test_show_job_macro_header_module4"}, {"nodeid": "tests/test_module4.py::test_show_job_macro_body_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 28, "domain": "test_show_job_macro_body_module4"}, {"nodeid": "tests/test_module4.py::test_show_jobs_macro_definition_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 35, "domain": "test_show_jobs_macro_definition_module4"}, {"nodeid": "tests/test_module4.py::test_show_jobs_macro_for_loop_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 40, "domain": "test_show_jobs_macro_for_loop_module4"}, {"nodeid": "tests/test_module4.py::test_show_jobs_macro_for_loop_body_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 49, "domain": "test_show_jobs_macro_for_loop_body_module4"}, {"nodeid": "tests/test_module4.py::test_import_macros_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 58, "domain": "test_import_macros_module4"}, {"nodeid": "tests/test_module4.py::test_index_template_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 63, "domain": "test_index_template_module4"}, {"nodeid": "tests/test_module4.py::test_display_all_jobs_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 69, "domain": "test_display_all_jobs_module4"}, {"nodeid": "tests/test_module4.py::test_app_jobs_route_jobs_module4", "type": "Function", "path": "tests/test_module4.py", "lineno": 74, "domain": "test_app_jobs_route_jobs_module4"}]}, {"nodeid": "tests/test_module5.py", "outcome": "passed", "children": [{"nodeid": "tests/test_module5.py::test_app_job_template_module5", "type": "Function", "path": "tests/test_module5.py", "lineno": 6, "domain": "test_app_job_template_module5"}, {"nodeid": "tests/test_module5.py::test_app_job_route_module5", "type": "Function", "path": "tests/test_module5.py", "lineno": 13, "domain": "test_app_job_route_module5"}, {"nodeid": "tests/test_module5.py::test_app_job_route_decorator_module5", "type": "Function", "path": "tests/test_module5.py", "lineno": 21, "domain": "test_app_job_route_decorator_module5"}, {"nodeid": "tests/test_module5.py::test_app_job_route_parameter_module5", "type": "Function", "path": "tests/test_module5.py", "lineno": 26, "domain": "test_app_job_route_parameter_module5"}, {"nodeid": "tests/test_module5.py::test_app_job_route_data_module5", "type": "Function", "path": "tests/test_module5.py", "lineno": 32, "domain": "test_app_job_route_data_module5"}, {"nodeid": "tests/test_module5.py::test_app_job_route_pass_data_module5", "type": "Function", "path": "tests/test_module5.py", "lineno": 38, "domain": "test_app_job_route_pass_data_module5"}]}, {"nodeid": "tests/test_module6.py", "outcome": "passed", "children": [{"nodeid": "tests/test_module6.py::test_employer_template_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 6, "domain": "test_employer_template_module6"}, {"nodeid": "tests/test_module6.py::test_employer_template_details_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 13, "domain": "test_employer_template_details_module6"}, {"nodeid": "tests/test_module6.py::test_employer_template_all_jobs_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 19, "domain": "test_employer_template_all_jobs_module6"}, {"nodeid": "tests/test_module6.py::test_employer_template_reviews_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 24, "domain": "test_employer_template_reviews_module6"}, {"nodeid": "tests/test_module6.py::test_employer_template_review_stars_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 29, "domain": "test_employer_template_review_stars_module6"}, {"nodeid": "tests/test_module6.py::test_employer_template_review_details_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 36, "domain": "test_employer_template_review_details_module6"}, {"nodeid": "tests/test_module6.py::test_app_employer_route_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 44, "domain": "test_app_employer_route_module6"}, {"nodeid": "tests/test_module6.py::test_app_employer_route_employers_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 54, "domain": "test_app_employer_route_employers_module6"}, {"nodeid": "tests/test_module6.py::test_app_employer_route_jobs_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 64, "domain": "test_app_employer_route_jobs_module6"}, {"nodeid": "tests/test_module6.py::test_app_employer_route_reviews_module6", "type": "Function", "path": "tests/test_module6.py", "lineno": 72, "domain": "test_app_employer_route_reviews_module6"}]}, {"nodeid": "tests/test_module7.py", "outcome": "passed", "children": [{"nodeid": "tests/test_module7.py::test_review_template_module7", "type": "Function", "path": "tests/test_module7.py", "lineno": 7, "domain": "test_review_template_module7"}, {"nodeid": "tests/test_module7.py::test_app_review_route_module7", "type": "Function", "path": "tests/test_module7.py", "lineno": 15, "domain": "test_app_review_route_module7"}, {"nodeid": "tests/test_module7.py::test_app_review_post_request_check_module7", "type": "Function", "path": "tests/test_module7.py", "lineno": 42, "domain": "test_app_review_post_request_check_module7"}, {"nodeid": "tests/test_module7.py::test_app_review_insert_review_module7", "type": "Function", "path": "tests/test_module7.py", "lineno": 92, "domain": "test_app_review_insert_review_module7"}, {"nodeid": "tests/test_module7.py::test_app_redirect_to_employer_module7", "type": "Function", "path": "tests/test_module7.py", "lineno": 98, "domain": "test_app_redirect_to_employer_module7"}, {"nodeid": "tests/test_module7.py::test_employer_review_button_module7", "type": "Function", "path": "tests/test_module7.py", "lineno": 105, "domain": "test_employer_review_button_module7"}]}, {"nodeid": "tests/__init__.py", "outcome": "passed", "children": [{"nodeid": "tests/test_module1.py", "type": "Module"}, {"nodeid": "tests/test_module2.py", "type": "Module"}, {"nodeid": "tests/test_module3.py", "type": "Module"}, {"nodeid": "tests/test_module4.py", "type": "Module"}, {"nodeid": "tests/test_module5.py", "type": "Module"}, {"nodeid": "tests/test_module6.py", "type": "Module"}, {"nodeid": "tests/test_module7.py", "type": "Module"}]}], "tests": [{"nodeid": "tests/test_module1.py::test_app_import_flask_module1", "path": "tests/test_module1.py", "lineno": 6, "domain": "test_app_import_flask_module1", "keywords": ["test_module1.py", "tests/__init__.py", "job-board", "test_app_import_flask_module1", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0005049705505371094, "outcome": "passed", "log": []}, "call": {"duration": 0.0016179084777832031, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module1.py", "lineno": 9, "message": "AssertionError: Have you imported the `Flask` class from `flask`?\nassert 'Flask' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module1.py", "lineno": 9, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_import_flask_module1\n    def test_app_import_flask_module1():\n>       assert 'Flask' in dir(app), 'Have you imported the `Flask` class from `flask`?'\nE       AssertionError: Have you imported the `Flask` class from `flask`?\nE       assert 'Flask' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module1.py:9: AssertionError"}, "teardown": {"duration": 0.0002129077911376953, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module1.py::test_app_create_flask_app_module1", "path": "tests/test_module1.py", "lineno": 13, "domain": "test_app_create_flask_app_module1", "keywords": ["test_module1.py", "tests/__init__.py", "job-board", "test_app_create_flask_app_module1", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0001583099365234375, "outcome": "passed", "log": []}, "call": {"duration": 0.0002658367156982422, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module1.py", "lineno": 16, "message": "AssertionError: Have you created an instance of the `Flask` class called `app`?\nassert 'app' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module1.py", "lineno": 16, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_create_flask_app_module1\n    def test_app_create_flask_app_module1():\n>       assert 'app' in dir(app), 'Have you created an instance of the `Flask` class called `app`?'\nE       AssertionError: Have you created an instance of the `Flask` class called `app`?\nE       assert 'app' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module1.py:16: AssertionError"}, "teardown": {"duration": 0.00020194053649902344, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module1.py::test_index_template_module1", "path": "tests/test_module1.py", "lineno": 18, "domain": "test_index_template_module1", "keywords": ["test_module1.py", "tests/__init__.py", "job-board", "test_index_template_module1", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00014209747314453125, "outcome": "passed", "log": []}, "call": {"duration": 0.00023603439331054688, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module1.py", "lineno": 21, "message": "AssertionError: The `templates` folder has not been created.\nassert False\n +  where False = <function isdir at 0x10ebe9b00>('jobs/templates')\n +    where <function isdir at 0x10ebe9b00> = <module 'posixpath' from '/usr/local/bin/../Cellar/python/3.7.6_1/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py'>.isdir\n +      where <module 'posixpath' from '/usr/local/bin/../Cellar/python/3.7.6_1/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py'> = os.path"}, "traceback": [{"path": "tests/test_module1.py", "lineno": 21, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_index_template_module1\n    def test_index_template_module1():\n>       assert os.path.isdir('jobs/templates'), 'The `templates` folder has not been created.'\nE       AssertionError: The `templates` folder has not been created.\nE       assert False\nE        +  where False = <function isdir at 0x10ebe9b00>('jobs/templates')\nE        +    where <function isdir at 0x10ebe9b00> = <module 'posixpath' from '/usr/local/bin/../Cellar/python/3.7.6_1/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py'>.isdir\nE        +      where <module 'posixpath' from '/usr/local/bin/../Cellar/python/3.7.6_1/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py'> = os.path\n\ntests/test_module1.py:21: AssertionError"}, "teardown": {"duration": 0.0001480579376220703, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module1.py::test_app_index_route_function_module1", "path": "tests/test_module1.py", "lineno": 25, "domain": "test_app_index_route_function_module1", "keywords": ["tests/__init__.py", "test_module1.py", "job-board", "test_app_index_route_function_module1", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00014209747314453125, "outcome": "passed", "log": []}, "call": {"duration": 0.00025391578674316406, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module1.py", "lineno": 28, "message": "AssertionError: Have you created an instance of the `Flask` class called `app`?\nassert 'app' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module1.py", "lineno": 28, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_index_route_function_module1\n    def test_app_index_route_function_module1():\n>       assert 'app' in dir(app), 'Have you created an instance of the `Flask` class called `app`?'\nE       AssertionError: Have you created an instance of the `Flask` class called `app`?\nE       assert 'app' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module1.py:28: AssertionError"}, "teardown": {"duration": 0.00015306472778320312, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module1.py::test_app_route_decoractors_module1", "path": "tests/test_module1.py", "lineno": 35, "domain": "test_app_route_decoractors_module1", "keywords": ["tests/__init__.py", "test_module1.py", "job-board", "test_app_route_decoractors_module1", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00014901161193847656, "outcome": "passed", "log": []}, "call": {"duration": 0.0002510547637939453, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module1.py", "lineno": 38, "message": "AssertionError: Have you created an instance of the `Flask` class called `app`?\nassert 'app' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module1.py", "lineno": 38, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_route_decoractors_module1\n    def test_app_route_decoractors_module1():\n>       assert 'app' in dir(app), 'Have you created an instance of the `Flask` class called `app`?'\nE       AssertionError: Have you created an instance of the `Flask` class called `app`?\nE       assert 'app' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module1.py:38: AssertionError"}, "teardown": {"duration": 0.00015687942504882812, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module2.py::test_layout_template_module2", "path": "tests/test_module2.py", "lineno": 7, "domain": "test_layout_template_module2", "keywords": ["tests/__init__.py", "job-board", "test_layout_template_module2", "test_module2.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0001628398895263672, "outcome": "passed", "log": []}, "call": {"duration": 0.0002040863037109375, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module2.py", "lineno": 10, "message": "AssertionError: The `layout.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('layout')"}, "traceback": [{"path": "tests/test_module2.py", "lineno": 10, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_layout_template_module2\n    def test_layout_template_module2():\n>       assert template_exists('layout'), 'The `layout.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `layout.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('layout')\n\ntests/test_module2.py:10: AssertionError"}, "teardown": {"duration": 0.0002129077911376953, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module2.py::test_add_bulma_css_framework_module2", "path": "tests/test_module2.py", "lineno": 11, "domain": "test_add_bulma_css_framework_module2", "keywords": ["tests/__init__.py", "job-board", "test_module2.py", "test_add_bulma_css_framework_module2", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002219676971435547, "outcome": "passed", "log": []}, "call": {"duration": 0.0002608299255371094, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module2.py", "lineno": 14, "message": "AssertionError: The `layout.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('layout')"}, "traceback": [{"path": "tests/test_module2.py", "lineno": 14, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_add_bulma_css_framework_module2\n    def test_add_bulma_css_framework_module2():\n>       assert template_exists('layout'), 'The `layout.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `layout.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('layout')\n\ntests/test_module2.py:14: AssertionError"}, "teardown": {"duration": 0.00021195411682128906, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module2.py::test_add_custom_css_module2", "path": "tests/test_module2.py", "lineno": 16, "domain": "test_add_custom_css_module2", "keywords": ["tests/__init__.py", "job-board", "test_module2.py", "test_add_custom_css_module2", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00015807151794433594, "outcome": "passed", "log": []}, "call": {"duration": 0.00022792816162109375, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module2.py", "lineno": 19, "message": "AssertionError: The `layout.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('layout')"}, "traceback": [{"path": "tests/test_module2.py", "lineno": 19, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_add_custom_css_module2\n    def test_add_custom_css_module2():\n>       assert template_exists('layout'), 'The `layout.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `layout.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('layout')\n\ntests/test_module2.py:19: AssertionError"}, "teardown": {"duration": 0.00016927719116210938, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module2.py::test_add_fontawesome_module2", "path": "tests/test_module2.py", "lineno": 21, "domain": "test_add_fontawesome_module2", "keywords": ["test_add_fontawesome_module2", "tests/__init__.py", "job-board", "test_module2.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00015282630920410156, "outcome": "passed", "log": []}, "call": {"duration": 0.00022292137145996094, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module2.py", "lineno": 24, "message": "AssertionError: The `layout.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('layout')"}, "traceback": [{"path": "tests/test_module2.py", "lineno": 24, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_add_fontawesome_module2\n    def test_add_fontawesome_module2():\n>       assert template_exists('layout'), 'The `layout.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `layout.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('layout')\n\ntests/test_module2.py:24: AssertionError"}, "teardown": {"duration": 0.0001647472381591797, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module2.py::test_extend_base_template_module2", "path": "tests/test_module2.py", "lineno": 30, "domain": "test_extend_base_template_module2", "keywords": ["tests/__init__.py", "job-board", "test_extend_base_template_module2", "test_module2.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.000164031982421875, "outcome": "passed", "log": []}, "call": {"duration": 0.0002269744873046875, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module2.py", "lineno": 33, "message": "AssertionError: The `index.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('index')"}, "traceback": [{"path": "tests/test_module2.py", "lineno": 33, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_extend_base_template_module2\n    def test_extend_base_template_module2():\n>       assert template_exists('index'), 'The `index.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `index.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('index')\n\ntests/test_module2.py:33: AssertionError"}, "teardown": {"duration": 0.00016689300537109375, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_import_sqlite_module3", "path": "tests/test_module3.py", "lineno": 6, "domain": "test_app_import_sqlite_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_import_sqlite_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.00021314620971679688, "outcome": "passed", "log": []}, "call": {"duration": 0.0002970695495605469, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 9, "message": "AssertionError: Have you imported `sqlite`?\nassert 'sqlite3' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 9, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_import_sqlite_module3\n    def test_app_import_sqlite_module3():\n>       assert 'sqlite3' in dir(app), 'Have you imported `sqlite`?'\nE       AssertionError: Have you imported `sqlite`?\nE       assert 'sqlite3' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:9: AssertionError"}, "teardown": {"duration": 0.0003008842468261719, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_import_g_module3", "path": "tests/test_module3.py", "lineno": 10, "domain": "test_app_import_g_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_import_g_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.0002067089080810547, "outcome": "passed", "log": []}, "call": {"duration": 0.0003490447998046875, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 13, "message": "AssertionError: Have you imported the `g` class from `flask`?\nassert 'g' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 13, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_import_g_module3\n    def test_app_import_g_module3():\n>       assert 'g' in dir(app), 'Have you imported the `g` class from `flask`?'\nE       AssertionError: Have you imported the `g` class from `flask`?\nE       assert 'g' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:13: AssertionError"}, "teardown": {"duration": 0.0002639293670654297, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_db_path_module3", "path": "tests/test_module3.py", "lineno": 14, "domain": "test_app_db_path_module3", "keywords": ["tests/__init__.py", "pytestmark", "test_app_db_path_module3", "job-board", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.00021123886108398438, "outcome": "passed", "log": []}, "call": {"duration": 0.0003631114959716797, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 17, "message": "AssertionError: Have you created a constant called `PATH`.\nassert 'PATH' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 17, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_db_path_module3\n    def test_app_db_path_module3():\n>       assert 'PATH' in dir(app), 'Have you created a constant called `PATH`.'\nE       AssertionError: Have you created a constant called `PATH`.\nE       assert 'PATH' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:17: AssertionError"}, "teardown": {"duration": 0.00022602081298828125, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_open_connection_get_attribute_module3", "path": "tests/test_module3.py", "lineno": 19, "domain": "test_app_open_connection_get_attribute_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_open_connection_get_attribute_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.00019502639770507812, "outcome": "passed", "log": []}, "call": {"duration": 0.0003349781036376953, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 22, "message": "AssertionError: Have you defined a function named `open_connection`.\nassert 'open_connection' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 22, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_open_connection_get_attribute_module3\n    def test_app_open_connection_get_attribute_module3():\n>       assert 'open_connection' in dir(app), 'Have you defined a function named `open_connection`.'\nE       AssertionError: Have you defined a function named `open_connection`.\nE       assert 'open_connection' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:22: AssertionError"}, "teardown": {"duration": 0.00028705596923828125, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_open_connection_connection_module3", "path": "tests/test_module3.py", "lineno": 24, "domain": "test_app_open_connection_connection_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_open_connection_connection_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.00021409988403320312, "outcome": "passed", "log": []}, "call": {"duration": 0.0003788471221923828, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 27, "message": "AssertionError: Have you imported the `g` class from `flask`?\nassert 'g' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 27, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_open_connection_connection_module3\n    def test_app_open_connection_connection_module3():\n>       assert 'g' in dir(app), 'Have you imported the `g` class from `flask`?'\nE       AssertionError: Have you imported the `g` class from `flask`?\nE       assert 'g' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:27: AssertionError"}, "teardown": {"duration": 0.00028324127197265625, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_open_connection_row_factory_module3", "path": "tests/test_module3.py", "lineno": 35, "domain": "test_app_open_connection_row_factory_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_open_connection_row_factory_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.00023484230041503906, "outcome": "passed", "log": []}, "call": {"duration": 0.00041484832763671875, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 38, "message": "AssertionError: Have you imported the `g` class from `flask`?\nassert 'g' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 38, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_open_connection_row_factory_module3\n    def test_app_open_connection_row_factory_module3():\n>       assert 'g' in dir(app), 'Have you imported the `g` class from `flask`?'\nE       AssertionError: Have you imported the `g` class from `flask`?\nE       assert 'g' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:38: AssertionError"}, "teardown": {"duration": 0.00022101402282714844, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_execute_sql_module3", "path": "tests/test_module3.py", "lineno": 45, "domain": "test_app_execute_sql_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_execute_sql_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.00019884109497070312, "outcome": "passed", "log": []}, "call": {"duration": 0.0003459453582763672, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 48, "message": "AssertionError: Have you created an instance of the `Flask` class called `app`?\nassert 'app' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 48, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_execute_sql_module3\n    def test_app_execute_sql_module3():\n>       assert 'app' in dir(app), 'Have you created an instance of the `Flask` class called `app`?'\nE       AssertionError: Have you created an instance of the `Flask` class called `app`?\nE       assert 'app' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:48: AssertionError"}, "teardown": {"duration": 0.0002830028533935547, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_execute_sql_parameters_module3", "path": "tests/test_module3.py", "lineno": 51, "domain": "test_app_execute_sql_parameters_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_execute_sql_parameters_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.00021982192993164062, "outcome": "passed", "log": []}, "call": {"duration": 0.00037980079650878906, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 54, "message": "AssertionError: Have you defined a function named `execute_sql`.\nassert 'execute_sql' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 54, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_execute_sql_parameters_module3\n    def test_app_execute_sql_parameters_module3():\n>       assert 'execute_sql' in dir(app), 'Have you defined a function named `execute_sql`.'\nE       AssertionError: Have you defined a function named `execute_sql`.\nE       assert 'execute_sql' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:54: AssertionError"}, "teardown": {"duration": 0.00032210350036621094, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_execute_sql_execute_module3", "path": "tests/test_module3.py", "lineno": 59, "domain": "test_app_execute_sql_execute_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_execute_sql_execute_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.00030112266540527344, "outcome": "passed", "log": []}, "call": {"duration": 0.00037598609924316406, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 62, "message": "AssertionError: Have you defined a function named `execute_sql`.\nassert 'execute_sql' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 62, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_execute_sql_execute_module3\n    def test_app_execute_sql_execute_module3():\n>       assert 'execute_sql' in dir(app), 'Have you defined a function named `execute_sql`.'\nE       AssertionError: Have you defined a function named `execute_sql`.\nE       assert 'execute_sql' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:62: AssertionError"}, "teardown": {"duration": 0.0002219676971435547, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_execute_sql_results_module3", "path": "tests/test_module3.py", "lineno": 64, "domain": "test_app_execute_sql_results_module3", "keywords": ["tests/__init__.py", "test_app_execute_sql_results_module3", "pytestmark", "job-board", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.000202178955078125, "outcome": "passed", "log": []}, "call": {"duration": 0.0003540515899658203, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 67, "message": "AssertionError: Have you defined a function named `execute_sql`.\nassert 'execute_sql' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 67, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_execute_sql_results_module3\n    def test_app_execute_sql_results_module3():\n>       assert 'execute_sql' in dir(app), 'Have you defined a function named `execute_sql`.'\nE       AssertionError: Have you defined a function named `execute_sql`.\nE       assert 'execute_sql' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:67: AssertionError"}, "teardown": {"duration": 0.00028395652770996094, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_close_connection_module3", "path": "tests/test_module3.py", "lineno": 77, "domain": "test_app_close_connection_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_close_connection_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.0002281665802001953, "outcome": "passed", "log": []}, "call": {"duration": 0.0003800392150878906, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 80, "message": "AssertionError: Have you defined a function named `close_connection`.\nassert 'close_connection' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 80, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_close_connection_module3\n    def test_app_close_connection_module3():\n>       assert 'close_connection' in dir(app), 'Have you defined a function named `close_connection`.'\nE       AssertionError: Have you defined a function named `close_connection`.\nE       assert 'close_connection' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:80: AssertionError"}, "teardown": {"duration": 0.00027298927307128906, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module3.py::test_app_close_connection_decorator_module3", "path": "tests/test_module3.py", "lineno": 83, "domain": "test_app_close_connection_decorator_module3", "keywords": ["tests/__init__.py", "pytestmark", "job-board", "test_app_close_connection_decorator_module3", "test_module3.py"], "outcome": "failed", "setup": {"duration": 0.000209808349609375, "outcome": "passed", "log": []}, "call": {"duration": 0.0003609657287597656, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module3.py", "lineno": 86, "message": "AssertionError: Have you defined a function named `close_connection`.\nassert 'close_connection' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module3.py", "lineno": 86, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_close_connection_decorator_module3\n    def test_app_close_connection_decorator_module3():\n>       assert 'close_connection' in dir(app), 'Have you defined a function named `close_connection`.'\nE       AssertionError: Have you defined a function named `close_connection`.\nE       assert 'close_connection' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module3.py:86: AssertionError"}, "teardown": {"duration": 0.00020933151245117188, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_template_macros_module4", "path": "tests/test_module4.py", "lineno": 6, "domain": "test_template_macros_module4", "keywords": ["tests/__init__.py", "job-board", "test_template_macros_module4", "test_module4.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00027489662170410156, "outcome": "passed", "log": []}, "call": {"duration": 0.0003151893615722656, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 9, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 9, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_template_macros_module4\n    def test_template_macros_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:9: AssertionError"}, "teardown": {"duration": 0.0003027915954589844, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_show_job_macro_definition_module4", "path": "tests/test_module4.py", "lineno": 10, "domain": "test_show_job_macro_definition_module4", "keywords": ["tests/__init__.py", "job-board", "test_show_job_macro_definition_module4", "test_module4.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00021409988403320312, "outcome": "passed", "log": []}, "call": {"duration": 0.00030994415283203125, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 13, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 13, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_show_job_macro_definition_module4\n    def test_show_job_macro_definition_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:13: AssertionError"}, "teardown": {"duration": 0.0002770423889160156, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_show_job_macro_html_module4", "path": "tests/test_module4.py", "lineno": 15, "domain": "test_show_job_macro_html_module4", "keywords": ["tests/__init__.py", "job-board", "test_module4.py", "test_show_job_macro_html_module4", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002319812774658203, "outcome": "passed", "log": []}, "call": {"duration": 0.00030112266540527344, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 18, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 18, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_show_job_macro_html_module4\n    def test_show_job_macro_html_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:18: AssertionError"}, "teardown": {"duration": 0.0002040863037109375, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_show_job_macro_header_module4", "path": "tests/test_module4.py", "lineno": 23, "domain": "test_show_job_macro_header_module4", "keywords": ["tests/__init__.py", "job-board", "test_show_job_macro_header_module4", "test_module4.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00019693374633789062, "outcome": "passed", "log": []}, "call": {"duration": 0.00028705596923828125, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 26, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 26, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_show_job_macro_header_module4\n    def test_show_job_macro_header_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:26: AssertionError"}, "teardown": {"duration": 0.0005609989166259766, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_show_job_macro_body_module4", "path": "tests/test_module4.py", "lineno": 28, "domain": "test_show_job_macro_body_module4", "keywords": ["tests/__init__.py", "job-board", "test_show_job_macro_body_module4", "test_module4.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00030493736267089844, "outcome": "passed", "log": []}, "call": {"duration": 0.0003368854522705078, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 31, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 31, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_show_job_macro_body_module4\n    def test_show_job_macro_body_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:31: AssertionError"}, "teardown": {"duration": 0.0002760887145996094, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_show_jobs_macro_definition_module4", "path": "tests/test_module4.py", "lineno": 35, "domain": "test_show_jobs_macro_definition_module4", "keywords": ["tests/__init__.py", "job-board", "test_module4.py", "test_show_jobs_macro_definition_module4", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00021886825561523438, "outcome": "passed", "log": []}, "call": {"duration": 0.00032210350036621094, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 38, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 38, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_show_jobs_macro_definition_module4\n    def test_show_jobs_macro_definition_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:38: AssertionError"}, "teardown": {"duration": 0.00033211708068847656, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_show_jobs_macro_for_loop_module4", "path": "tests/test_module4.py", "lineno": 40, "domain": "test_show_jobs_macro_for_loop_module4", "keywords": ["tests/__init__.py", "job-board", "test_module4.py", "test_show_jobs_macro_for_loop_module4", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002701282501220703, "outcome": "passed", "log": []}, "call": {"duration": 0.0003120899200439453, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 43, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 43, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_show_jobs_macro_for_loop_module4\n    def test_show_jobs_macro_for_loop_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:43: AssertionError"}, "teardown": {"duration": 0.0002608299255371094, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_show_jobs_macro_for_loop_body_module4", "path": "tests/test_module4.py", "lineno": 49, "domain": "test_show_jobs_macro_for_loop_body_module4", "keywords": ["tests/__init__.py", "job-board", "test_module4.py", "test_show_jobs_macro_for_loop_body_module4", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00021982192993164062, "outcome": "passed", "log": []}, "call": {"duration": 0.0003540515899658203, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 52, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 52, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_show_jobs_macro_for_loop_body_module4\n    def test_show_jobs_macro_for_loop_body_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:52: AssertionError"}, "teardown": {"duration": 0.00027489662170410156, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_import_macros_module4", "path": "tests/test_module4.py", "lineno": 58, "domain": "test_import_macros_module4", "keywords": ["tests/__init__.py", "job-board", "test_import_macros_module4", "test_module4.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00021386146545410156, "outcome": "passed", "log": []}, "call": {"duration": 0.00037789344787597656, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 61, "message": "AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('_macros')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 61, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_import_macros_module4\n    def test_import_macros_module4():\n>       assert template_exists('_macros'), 'The `_macros.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `_macros.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('_macros')\n\ntests/test_module4.py:61: AssertionError"}, "teardown": {"duration": 0.000286102294921875, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_index_template_module4", "path": "tests/test_module4.py", "lineno": 63, "domain": "test_index_template_module4", "keywords": ["tests/__init__.py", "test_index_template_module4", "job-board", "test_module4.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00021386146545410156, "outcome": "passed", "log": []}, "call": {"duration": 0.00043487548828125, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 66, "message": "AssertionError: The `index.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('index')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 66, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_index_template_module4\n    def test_index_template_module4():\n>       assert template_exists('index'), 'The `index.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `index.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('index')\n\ntests/test_module4.py:66: AssertionError"}, "teardown": {"duration": 0.00021767616271972656, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_display_all_jobs_module4", "path": "tests/test_module4.py", "lineno": 69, "domain": "test_display_all_jobs_module4", "keywords": ["tests/__init__.py", "job-board", "test_display_all_jobs_module4", "test_module4.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00020384788513183594, "outcome": "passed", "log": []}, "call": {"duration": 0.00036406517028808594, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 72, "message": "AssertionError: The `index.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('index')"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 72, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_display_all_jobs_module4\n    def test_display_all_jobs_module4():\n>       assert template_exists('index'), 'The `index.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `index.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('index')\n\ntests/test_module4.py:72: AssertionError"}, "teardown": {"duration": 0.00028014183044433594, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module4.py::test_app_jobs_route_jobs_module4", "path": "tests/test_module4.py", "lineno": 74, "domain": "test_app_jobs_route_jobs_module4", "keywords": ["tests/__init__.py", "job-board", "test_app_jobs_route_jobs_module4", "test_module4.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00021195411682128906, "outcome": "passed", "log": []}, "call": {"duration": 0.0004210472106933594, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module4.py", "lineno": 77, "message": "AssertionError: Have you created the `jobs` function?\nassert 'jobs' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module4.py", "lineno": 77, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_jobs_route_jobs_module4\n    def test_app_jobs_route_jobs_module4():\n>       assert 'jobs' in dir(app), 'Have you created the `jobs` function?'\nE       AssertionError: Have you created the `jobs` function?\nE       assert 'jobs' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module4.py:77: AssertionError"}, "teardown": {"duration": 0.00028204917907714844, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module5.py::test_app_job_template_module5", "path": "tests/test_module5.py", "lineno": 6, "domain": "test_app_job_template_module5", "keywords": ["tests/__init__.py", "job-board", "test_module5.py", "test_app_job_template_module5", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002281665802001953, "outcome": "passed", "log": []}, "call": {"duration": 0.0002989768981933594, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module5.py", "lineno": 9, "message": "AssertionError: The `job.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('job')"}, "traceback": [{"path": "tests/test_module5.py", "lineno": 9, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_job_template_module5\n    def test_app_job_template_module5():\n>       assert template_exists('job'), 'The `job.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `job.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('job')\n\ntests/test_module5.py:9: AssertionError"}, "teardown": {"duration": 0.0002009868621826172, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module5.py::test_app_job_route_module5", "path": "tests/test_module5.py", "lineno": 13, "domain": "test_app_job_route_module5", "keywords": ["tests/__init__.py", "job-board", "test_module5.py", "test_app_job_route_module5", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00019407272338867188, "outcome": "passed", "log": []}, "call": {"duration": 0.0003428459167480469, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module5.py", "lineno": 16, "message": "AssertionError: Have you created the `job` function?\nassert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module5.py", "lineno": 16, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_job_route_module5\n    def test_app_job_route_module5():\n>       assert 'job' in dir(app), 'Have you created the `job` function?'\nE       AssertionError: Have you created the `job` function?\nE       assert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module5.py:16: AssertionError"}, "teardown": {"duration": 0.00023508071899414062, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module5.py::test_app_job_route_decorator_module5", "path": "tests/test_module5.py", "lineno": 21, "domain": "test_app_job_route_decorator_module5", "keywords": ["tests/__init__.py", "job-board", "test_module5.py", "test_app_job_route_decorator_module5", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00031495094299316406, "outcome": "passed", "log": []}, "call": {"duration": 0.0008521080017089844, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module5.py", "lineno": 24, "message": "AssertionError: Have you created the `job` function?\nassert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module5.py", "lineno": 24, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_job_route_decorator_module5\n    def test_app_job_route_decorator_module5():\n>       assert 'job' in dir(app), 'Have you created the `job` function?'\nE       AssertionError: Have you created the `job` function?\nE       assert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module5.py:24: AssertionError"}, "teardown": {"duration": 0.0002827644348144531, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module5.py::test_app_job_route_parameter_module5", "path": "tests/test_module5.py", "lineno": 26, "domain": "test_app_job_route_parameter_module5", "keywords": ["test_app_job_route_parameter_module5", "tests/__init__.py", "job-board", "test_module5.py", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00024199485778808594, "outcome": "passed", "log": []}, "call": {"duration": 0.00038313865661621094, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module5.py", "lineno": 29, "message": "AssertionError: Have you created the `job` function?\nassert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module5.py", "lineno": 29, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_job_route_parameter_module5\n    def test_app_job_route_parameter_module5():\n>       assert 'job' in dir(app), 'Have you created the `job` function?'\nE       AssertionError: Have you created the `job` function?\nE       assert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module5.py:29: AssertionError"}, "teardown": {"duration": 0.0002570152282714844, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module5.py::test_app_job_route_data_module5", "path": "tests/test_module5.py", "lineno": 32, "domain": "test_app_job_route_data_module5", "keywords": ["tests/__init__.py", "job-board", "test_module5.py", "test_app_job_route_data_module5", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002090930938720703, "outcome": "passed", "log": []}, "call": {"duration": 0.00035381317138671875, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module5.py", "lineno": 35, "message": "AssertionError: Have you created the `job` function?\nassert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module5.py", "lineno": 35, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_job_route_data_module5\n    def test_app_job_route_data_module5():\n>       assert 'job' in dir(app), 'Have you created the `job` function?'\nE       AssertionError: Have you created the `job` function?\nE       assert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module5.py:35: AssertionError"}, "teardown": {"duration": 0.0002548694610595703, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module5.py::test_app_job_route_pass_data_module5", "path": "tests/test_module5.py", "lineno": 38, "domain": "test_app_job_route_pass_data_module5", "keywords": ["tests/__init__.py", "job-board", "test_module5.py", "test_app_job_route_pass_data_module5", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002079010009765625, "outcome": "passed", "log": []}, "call": {"duration": 0.00036406517028808594, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module5.py", "lineno": 41, "message": "AssertionError: Have you created the `job` function?\nassert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module5.py", "lineno": 41, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_job_route_pass_data_module5\n    def test_app_job_route_pass_data_module5():\n>       assert 'job' in dir(app), 'Have you created the `job` function?'\nE       AssertionError: Have you created the `job` function?\nE       assert 'job' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module5.py:41: AssertionError"}, "teardown": {"duration": 0.00034308433532714844, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_employer_template_module6", "path": "tests/test_module6.py", "lineno": 6, "domain": "test_employer_template_module6", "keywords": ["tests/__init__.py", "test_module6.py", "test_employer_template_module6", "job-board", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002548694610595703, "outcome": "passed", "log": []}, "call": {"duration": 0.00031375885009765625, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 9, "message": "AssertionError: The `employer.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('employer')"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 9, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_employer_template_module6\n    def test_employer_template_module6():\n>       assert template_exists('employer'), 'The `employer.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `employer.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('employer')\n\ntests/test_module6.py:9: AssertionError"}, "teardown": {"duration": 0.00028896331787109375, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_employer_template_details_module6", "path": "tests/test_module6.py", "lineno": 13, "domain": "test_employer_template_details_module6", "keywords": ["tests/__init__.py", "test_module6.py", "job-board", "test_employer_template_details_module6", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00021886825561523438, "outcome": "passed", "log": []}, "call": {"duration": 0.00030112266540527344, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 16, "message": "AssertionError: The `employer.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('employer')"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 16, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_employer_template_details_module6\n    def test_employer_template_details_module6():\n>       assert template_exists('employer'), 'The `employer.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `employer.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('employer')\n\ntests/test_module6.py:16: AssertionError"}, "teardown": {"duration": 0.0002040863037109375, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_employer_template_all_jobs_module6", "path": "tests/test_module6.py", "lineno": 19, "domain": "test_employer_template_all_jobs_module6", "keywords": ["tests/__init__.py", "test_module6.py", "job-board", "test_employer_template_all_jobs_module6", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0001990795135498047, "outcome": "passed", "log": []}, "call": {"duration": 0.0002779960632324219, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 22, "message": "AssertionError: The `employer.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('employer')"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 22, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_employer_template_all_jobs_module6\n    def test_employer_template_all_jobs_module6():\n>       assert template_exists('employer'), 'The `employer.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `employer.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('employer')\n\ntests/test_module6.py:22: AssertionError"}, "teardown": {"duration": 0.0002779960632324219, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_employer_template_reviews_module6", "path": "tests/test_module6.py", "lineno": 24, "domain": "test_employer_template_reviews_module6", "keywords": ["tests/__init__.py", "test_module6.py", "job-board", "test_employer_template_reviews_module6", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0005521774291992188, "outcome": "passed", "log": []}, "call": {"duration": 0.0007538795471191406, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 27, "message": "AssertionError: The `employer.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('employer')"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 27, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_employer_template_reviews_module6\n    def test_employer_template_reviews_module6():\n>       assert template_exists('employer'), 'The `employer.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `employer.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('employer')\n\ntests/test_module6.py:27: AssertionError"}, "teardown": {"duration": 0.0003018379211425781, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_employer_template_review_stars_module6", "path": "tests/test_module6.py", "lineno": 29, "domain": "test_employer_template_review_stars_module6", "keywords": ["tests/__init__.py", "test_module6.py", "job-board", "test_employer_template_review_stars_module6", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00022792816162109375, "outcome": "passed", "log": []}, "call": {"duration": 0.0003199577331542969, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 32, "message": "AssertionError: The `employer.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('employer')"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 32, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_employer_template_review_stars_module6\n    def test_employer_template_review_stars_module6():\n>       assert template_exists('employer'), 'The `employer.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `employer.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('employer')\n\ntests/test_module6.py:32: AssertionError"}, "teardown": {"duration": 0.0002372264862060547, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_employer_template_review_details_module6", "path": "tests/test_module6.py", "lineno": 36, "domain": "test_employer_template_review_details_module6", "keywords": ["tests/__init__.py", "test_module6.py", "test_employer_template_review_details_module6", "job-board", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00020933151245117188, "outcome": "passed", "log": []}, "call": {"duration": 0.0002918243408203125, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 39, "message": "AssertionError: The `employer.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('employer')"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 39, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_employer_template_review_details_module6\n    def test_employer_template_review_details_module6():\n>       assert template_exists('employer'), 'The `employer.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `employer.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('employer')\n\ntests/test_module6.py:39: AssertionError"}, "teardown": {"duration": 0.00026702880859375, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_app_employer_route_module6", "path": "tests/test_module6.py", "lineno": 44, "domain": "test_app_employer_route_module6", "keywords": ["tests/__init__.py", "test_module6.py", "job-board", "test_app_employer_route_module6", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00022792816162109375, "outcome": "passed", "log": []}, "call": {"duration": 0.0004200935363769531, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 47, "message": "AssertionError: Have you created the `employer` function?\nassert 'employer' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 47, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_employer_route_module6\n    def test_app_employer_route_module6():\n>       assert 'employer' in dir(app), 'Have you created the `employer` function?'\nE       AssertionError: Have you created the `employer` function?\nE       assert 'employer' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module6.py:47: AssertionError"}, "teardown": {"duration": 0.0002980232238769531, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_app_employer_route_employers_module6", "path": "tests/test_module6.py", "lineno": 54, "domain": "test_app_employer_route_employers_module6", "keywords": ["tests/__init__.py", "test_module6.py", "job-board", "test_app_employer_route_employers_module6", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00022292137145996094, "outcome": "passed", "log": []}, "call": {"duration": 0.0004131793975830078, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 57, "message": "AssertionError: Have you created the `employer` function?\nassert 'employer' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 57, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_employer_route_employers_module6\n    def test_app_employer_route_employers_module6():\n>       assert 'employer' in dir(app), 'Have you created the `employer` function?'\nE       AssertionError: Have you created the `employer` function?\nE       assert 'employer' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module6.py:57: AssertionError"}, "teardown": {"duration": 0.00026702880859375, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_app_employer_route_jobs_module6", "path": "tests/test_module6.py", "lineno": 64, "domain": "test_app_employer_route_jobs_module6", "keywords": ["tests/__init__.py", "test_module6.py", "job-board", "test_app_employer_route_jobs_module6", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00021028518676757812, "outcome": "passed", "log": []}, "call": {"duration": 0.0003571510314941406, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 67, "message": "AssertionError: Have you created the `employer` function?\nassert 'employer' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 67, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_employer_route_jobs_module6\n    def test_app_employer_route_jobs_module6():\n>       assert 'employer' in dir(app), 'Have you created the `employer` function?'\nE       AssertionError: Have you created the `employer` function?\nE       assert 'employer' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module6.py:67: AssertionError"}, "teardown": {"duration": 0.00021600723266601562, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module6.py::test_app_employer_route_reviews_module6", "path": "tests/test_module6.py", "lineno": 72, "domain": "test_app_employer_route_reviews_module6", "keywords": ["tests/__init__.py", "test_module6.py", "job-board", "test_app_employer_route_reviews_module6", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0003371238708496094, "outcome": "passed", "log": []}, "call": {"duration": 0.0003829002380371094, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module6.py", "lineno": 75, "message": "AssertionError: Have you created the `employer` function?\nassert 'employer' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module6.py", "lineno": 75, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_employer_route_reviews_module6\n    def test_app_employer_route_reviews_module6():\n>       assert 'employer' in dir(app), 'Have you created the `employer` function?'\nE       AssertionError: Have you created the `employer` function?\nE       assert 'employer' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module6.py:75: AssertionError"}, "teardown": {"duration": 0.0002739429473876953, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module7.py::test_review_template_module7", "path": "tests/test_module7.py", "lineno": 7, "domain": "test_review_template_module7", "keywords": ["tests/__init__.py", "test_module7.py", "job-board", "test_review_template_module7", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00030112266540527344, "outcome": "passed", "log": []}, "call": {"duration": 0.00033211708068847656, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module7.py", "lineno": 10, "message": "AssertionError: The `review.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('review')"}, "traceback": [{"path": "tests/test_module7.py", "lineno": 10, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_review_template_module7\n    def test_review_template_module7():\n>       assert template_exists('review'), 'The `review.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `review.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('review')\n\ntests/test_module7.py:10: AssertionError"}, "teardown": {"duration": 0.00024819374084472656, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module7.py::test_app_review_route_module7", "path": "tests/test_module7.py", "lineno": 15, "domain": "test_app_review_route_module7", "keywords": ["tests/__init__.py", "test_module7.py", "job-board", "test_app_review_route_module7", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00020623207092285156, "outcome": "passed", "log": []}, "call": {"duration": 0.0003521442413330078, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module7.py", "lineno": 18, "message": "AssertionError: Have you created the `review` function?\nassert 'review' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module7.py", "lineno": 18, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_review_route_module7\n    def test_app_review_route_module7():\n>       assert 'review' in dir(app), 'Have you created the `review` function?'\nE       AssertionError: Have you created the `review` function?\nE       assert 'review' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module7.py:18: AssertionError"}, "teardown": {"duration": 0.0002338886260986328, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module7.py::test_app_review_post_request_check_module7", "path": "tests/test_module7.py", "lineno": 42, "domain": "test_app_review_post_request_check_module7", "keywords": ["tests/__init__.py", "test_module7.py", "job-board", "test_app_review_post_request_check_module7", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00023794174194335938, "outcome": "passed", "log": []}, "call": {"duration": 0.0005230903625488281, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module7.py", "lineno": 45, "message": "AssertionError: Have you created the `review` function?\nassert 'review' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module7.py", "lineno": 45, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_review_post_request_check_module7\n    def test_app_review_post_request_check_module7():\n>       assert 'review' in dir(app), 'Have you created the `review` function?'\nE       AssertionError: Have you created the `review` function?\nE       assert 'review' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module7.py:45: AssertionError"}, "teardown": {"duration": 0.0003590583801269531, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module7.py::test_app_review_insert_review_module7", "path": "tests/test_module7.py", "lineno": 92, "domain": "test_app_review_insert_review_module7", "keywords": ["tests/__init__.py", "test_module7.py", "job-board", "test_app_review_insert_review_module7", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002307891845703125, "outcome": "passed", "log": []}, "call": {"duration": 0.0003979206085205078, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module7.py", "lineno": 95, "message": "AssertionError: Have you created the `review` function?\nassert 'review' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module7.py", "lineno": 95, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_review_insert_review_module7\n    def test_app_review_insert_review_module7():\n>       assert 'review' in dir(app), 'Have you created the `review` function?'\nE       AssertionError: Have you created the `review` function?\nE       assert 'review' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module7.py:95: AssertionError"}, "teardown": {"duration": 0.0002529621124267578, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module7.py::test_app_redirect_to_employer_module7", "path": "tests/test_module7.py", "lineno": 98, "domain": "test_app_redirect_to_employer_module7", "keywords": ["tests/__init__.py", "test_module7.py", "job-board", "test_app_redirect_to_employer_module7", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.00020885467529296875, "outcome": "passed", "log": []}, "call": {"duration": 0.0003540515899658203, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module7.py", "lineno": 101, "message": "AssertionError: Have you created the `review` function?\nassert 'review' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\n +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)"}, "traceback": [{"path": "tests/test_module7.py", "lineno": 101, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_app_redirect_to_employer_module7\n    def test_app_redirect_to_employer_module7():\n>       assert 'review' in dir(app), 'Have you created the `review` function?'\nE       AssertionError: Have you created the `review` function?\nE       assert 'review' in ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...]\nE        +  where ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', ...] = dir(app)\n\ntests/test_module7.py:101: AssertionError"}, "teardown": {"duration": 0.0002162456512451172, "outcome": "passed", "log": []}}, {"nodeid": "tests/test_module7.py::test_employer_review_button_module7", "path": "tests/test_module7.py", "lineno": 105, "domain": "test_employer_review_button_module7", "keywords": ["tests/__init__.py", "test_module7.py", "job-board", "test_employer_review_button_module7", "pytestmark"], "outcome": "failed", "setup": {"duration": 0.0002040863037109375, "outcome": "passed", "log": []}, "call": {"duration": 0.0003838539123535156, "outcome": "failed", "crash": {"path": "/Users/patelk2/python/projects/job-board/tests/test_module7.py", "lineno": 108, "message": "AssertionError: The `employer.html` template does not exist in the `templates` folder.\nassert False\n +  where False = template_exists('employer')"}, "traceback": [{"path": "tests/test_module7.py", "lineno": 108, "message": "AssertionError"}], "log": [], "longrepr": "@pytest.mark.test_employer_review_button_module7\n    def test_employer_review_button_module7():\n>       assert template_exists('employer'), 'The `employer.html` template does not exist in the `templates` folder.'\nE       AssertionError: The `employer.html` template does not exist in the `templates` folder.\nE       assert False\nE        +  where False = template_exists('employer')\n\ntests/test_module7.py:108: AssertionError"}, "teardown": {"duration": 0.0002789497375488281, "outcome": "passed", "log": []}}]}